version: 1.2
workflows:
 - name: Zip_Column_Content
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_zip_column.wdl
   testParameterFiles:
    - empty.json
 - name: Concatenate_Column_Content
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cat_column.wdl
   testParameterFiles:
    - empty.json
 - name: Import_SE_reads
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_import_se_reads.wdl
   testParameterFiles:
    - empty.json
 - name: Import_PE_reads
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_import_pe_reads.wdl
   testParameterFiles:
    - empty.json
 - name: BAM_to_FASTQ_SE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_bam_to_fastq_se.wdl
   testParameterFiles:
    - empty.json
 - name: BAM_to_FASTQ_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_bam_to_fastq_pe.wdl
   testParameterFiles:
    - empty.json
 - name: BaseSpace_Fetch
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_basespace_fetch.wdl
   testParameterFiles:
    - empty.json
 - name: Transfer_Column_Content
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_transfer_column.wdl
   testParameterFiles:
    - empty.json
 - name: Transfer_Assembly_Files
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_transfer_assembly_files.wdl
   testParameterFiles:
    - empty.json
